export interface HistoricalEntity {
  name: string;
  numistaIssuer: string;
  modernCountries: string[];
  color?: string;
}

export interface HistoricalPeriod {
  startYear: number;
  endYear: number;
  entities: Record<string, HistoricalEntity>;
}

const HISTORICAL_PERIODS: HistoricalPeriod[] = [
  {
    startYear: 1700,
    endYear: 1721,
    entities: {
      "Ottoman Empire": { name: "Ottoman Empire", numistaIssuer: "ottoman-empire", modernCountries: ["TUR", "SYR", "IRQ", "EGY", "LBY", "TUN", "DZA", "SAU", "YEM", "JOR", "LBN", "PSE", "ISR", "GRC", "BGR", "ROU", "SRB", "BIH", "MNE", "ALB", "MKD", "HUN", "HRV"], color: "#8B0000" },
      "Russian Empire": { name: "Russian Empire", numistaIssuer: "russia-empire", modernCountries: ["RUS", "UKR", "BLR", "LTU", "LVA", "EST", "FIN", "POL", "GEO", "ARM", "AZE", "KAZ", "UZB", "TKM", "TJK", "KGZ", "MDA"], color: "#1a237e" },
      "Kingdom of France": { name: "Kingdom of France", numistaIssuer: "france", modernCountries: ["FRA"], color: "#1565c0" },
      "Kingdom of Spain": { name: "Kingdom of Spain", numistaIssuer: "spain", modernCountries: ["ESP"], color: "#e65100" },
      "Kingdom of Portugal": { name: "Kingdom of Portugal", numistaIssuer: "portugal", modernCountries: ["PRT"], color: "#2e7d32" },
      "Holy Roman Empire": { name: "Holy Roman Empire", numistaIssuer: "holy-roman-empire", modernCountries: ["DEU", "AUT", "CZE", "CHE", "LIE", "LUX", "BEL", "NLD", "SVN", "ITA"], color: "#f9a825" },
      "Kingdom of Great Britain": { name: "Kingdom of Great Britain", numistaIssuer: "united-kingdom", modernCountries: ["GBR", "IRL"], color: "#c62828" },
      "Kingdom of Sweden": { name: "Kingdom of Sweden", numistaIssuer: "sweden", modernCountries: ["SWE", "NOR"], color: "#0277bd" },
      "Kingdom of Denmark": { name: "Kingdom of Denmark", numistaIssuer: "denmark", modernCountries: ["DNK", "ISL"], color: "#ad1457" },
      "Qing Dynasty": { name: "Qing Dynasty", numistaIssuer: "china-empire", modernCountries: ["CHN", "TWN", "MNG"], color: "#d84315" },
      "Mughal Empire": { name: "Mughal Empire", numistaIssuer: "mughal-empire", modernCountries: ["IND", "PAK", "BGD", "AFG"], color: "#4a148c" },
      "Safavid Persia": { name: "Safavid Persia", numistaIssuer: "iran", modernCountries: ["IRN"], color: "#00695c" },
      "Tokugawa Japan": { name: "Tokugawa Japan", numistaIssuer: "japan", modernCountries: ["JPN"], color: "#bf360c" },
      "Joseon Korea": { name: "Joseon Korea", numistaIssuer: "korea", modernCountries: ["KOR", "PRK"], color: "#33691e" },
      "Siam": { name: "Kingdom of Siam", numistaIssuer: "thailand", modernCountries: ["THA"], color: "#4527a0" },
      "Ethiopia": { name: "Ethiopian Empire", numistaIssuer: "ethiopia", modernCountries: ["ETH"], color: "#1b5e20" },
      "Morocco": { name: "Sultanate of Morocco", numistaIssuer: "morocco", modernCountries: ["MAR"], color: "#e53935" },
    },
  },
  {
    startYear: 1722,
    endYear: 1791,
    entities: {
      "Ottoman Empire": { name: "Ottoman Empire", numistaIssuer: "ottoman-empire", modernCountries: ["TUR", "SYR", "IRQ", "EGY", "LBY", "TUN", "SAU", "YEM", "JOR", "LBN", "PSE", "ISR", "GRC", "BGR", "ROU", "SRB", "BIH", "MNE", "ALB", "MKD"], color: "#8B0000" },
      "Russian Empire": { name: "Russian Empire", numistaIssuer: "russia-empire", modernCountries: ["RUS", "UKR", "BLR", "LTU", "LVA", "EST", "FIN", "GEO", "ARM", "AZE", "KAZ", "UZB", "TKM", "TJK", "KGZ", "MDA"], color: "#1a237e" },
      "Kingdom of France": { name: "Kingdom of France", numistaIssuer: "france", modernCountries: ["FRA"], color: "#1565c0" },
      "Kingdom of Spain": { name: "Kingdom of Spain", numistaIssuer: "spain", modernCountries: ["ESP"], color: "#e65100" },
      "Kingdom of Portugal": { name: "Kingdom of Portugal", numistaIssuer: "portugal", modernCountries: ["PRT"], color: "#2e7d32" },
      "Habsburg Monarchy": { name: "Habsburg Monarchy", numistaIssuer: "austria", modernCountries: ["AUT", "CZE", "HUN", "SVK", "HRV", "SVN", "ITA", "BEL"], color: "#f9a825" },
      "Kingdom of Prussia": { name: "Kingdom of Prussia", numistaIssuer: "prussia", modernCountries: ["DEU", "POL"], color: "#37474f" },
      "Kingdom of Great Britain": { name: "Kingdom of Great Britain", numistaIssuer: "united-kingdom", modernCountries: ["GBR", "IRL"], color: "#c62828" },
      "Dutch Republic": { name: "Dutch Republic", numistaIssuer: "netherlands", modernCountries: ["NLD", "LUX"], color: "#ff6f00" },
      "Kingdom of Sweden": { name: "Kingdom of Sweden", numistaIssuer: "sweden", modernCountries: ["SWE"], color: "#0277bd" },
      "Kingdom of Denmark-Norway": { name: "Denmark-Norway", numistaIssuer: "denmark", modernCountries: ["DNK", "NOR", "ISL"], color: "#ad1457" },
      "Swiss Confederacy": { name: "Swiss Confederacy", numistaIssuer: "switzerland", modernCountries: ["CHE", "LIE"], color: "#b71c1c" },
      "Qing Dynasty": { name: "Qing Dynasty", numistaIssuer: "china-empire", modernCountries: ["CHN", "TWN", "MNG"], color: "#d84315" },
      "Mughal Empire": { name: "Mughal Empire", numistaIssuer: "mughal-empire", modernCountries: ["IND", "PAK", "BGD"], color: "#4a148c" },
      "Afsharid/Qajar Persia": { name: "Persia", numistaIssuer: "iran", modernCountries: ["IRN", "AFG"], color: "#00695c" },
      "Tokugawa Japan": { name: "Tokugawa Japan", numistaIssuer: "japan", modernCountries: ["JPN"], color: "#bf360c" },
    },
  },
  {
    startYear: 1792,
    endYear: 1814,
    entities: {
      "French Empire": { name: "French Empire (Napoleon)", numistaIssuer: "france", modernCountries: ["FRA", "BEL", "NLD", "LUX", "ITA", "CHE"], color: "#1565c0" },
      "Ottoman Empire": { name: "Ottoman Empire", numistaIssuer: "ottoman-empire", modernCountries: ["TUR", "SYR", "IRQ", "EGY", "LBY", "TUN", "SAU", "YEM", "JOR", "LBN", "PSE", "ISR", "GRC", "BGR", "ROU", "SRB", "BIH", "MNE", "ALB", "MKD"], color: "#8B0000" },
      "Russian Empire": { name: "Russian Empire", numistaIssuer: "russia-empire", modernCountries: ["RUS", "UKR", "BLR", "LTU", "LVA", "EST", "FIN", "GEO", "ARM", "AZE", "KAZ", "UZB", "TKM", "TJK", "KGZ", "MDA", "POL"], color: "#1a237e" },
      "Kingdom of Spain": { name: "Kingdom of Spain", numistaIssuer: "spain", modernCountries: ["ESP", "PRT"], color: "#e65100" },
      "Austrian Empire": { name: "Austrian Empire", numistaIssuer: "austria", modernCountries: ["AUT", "CZE", "HUN", "SVK", "HRV", "SVN"], color: "#f9a825" },
      "Kingdom of Prussia": { name: "Kingdom of Prussia", numistaIssuer: "prussia", modernCountries: ["DEU"], color: "#37474f" },
      "United Kingdom": { name: "United Kingdom", numistaIssuer: "united-kingdom", modernCountries: ["GBR", "IRL"], color: "#c62828" },
      "Kingdom of Sweden": { name: "Kingdom of Sweden", numistaIssuer: "sweden", modernCountries: ["SWE", "NOR"], color: "#0277bd" },
      "Kingdom of Denmark": { name: "Kingdom of Denmark", numistaIssuer: "denmark", modernCountries: ["DNK", "ISL"], color: "#ad1457" },
      "Qing Dynasty": { name: "Qing Dynasty", numistaIssuer: "china-empire", modernCountries: ["CHN", "TWN", "MNG"], color: "#d84315" },
      "United States": { name: "United States", numistaIssuer: "united-states", modernCountries: ["USA"], color: "#1976d2" },
    },
  },
  {
    startYear: 1815,
    endYear: 1866,
    entities: {
      "Ottoman Empire": { name: "Ottoman Empire", numistaIssuer: "ottoman-empire", modernCountries: ["TUR", "SYR", "IRQ", "EGY", "LBY", "TUN", "DZA", "SAU", "YEM", "JOR", "LBN", "PSE", "ISR", "GRC", "BGR", "ROU", "SRB", "BIH", "MNE", "ALB", "MKD"], color: "#8B0000" },
      "Russian Empire": { name: "Russian Empire", numistaIssuer: "russia-empire", modernCountries: ["RUS", "UKR", "BLR", "LTU", "LVA", "EST", "FIN", "GEO", "ARM", "AZE", "KAZ", "UZB", "TKM", "TJK", "KGZ", "MDA", "POL"], color: "#1a237e" },
      "Kingdom of France": { name: "Kingdom of France", numistaIssuer: "france", modernCountries: ["FRA", "DZA"], color: "#1565c0" },
      "Kingdom of Spain": { name: "Kingdom of Spain", numistaIssuer: "spain", modernCountries: ["ESP"], color: "#e65100" },
      "Kingdom of Portugal": { name: "Kingdom of Portugal", numistaIssuer: "portugal", modernCountries: ["PRT"], color: "#2e7d32" },
      "Austrian Empire": { name: "Austrian Empire", numistaIssuer: "austria", modernCountries: ["AUT", "CZE", "HUN", "SVK", "HRV", "SVN", "ITA"], color: "#f9a825" },
      "Kingdom of Prussia": { name: "Kingdom of Prussia", numistaIssuer: "prussia", modernCountries: ["DEU"], color: "#37474f" },
      "United Kingdom": { name: "United Kingdom", numistaIssuer: "united-kingdom", modernCountries: ["GBR", "IRL"], color: "#c62828" },
      "Kingdom of the Netherlands": { name: "Kingdom of the Netherlands", numistaIssuer: "netherlands", modernCountries: ["NLD", "BEL", "LUX"], color: "#ff6f00" },
      "Switzerland": { name: "Switzerland", numistaIssuer: "switzerland", modernCountries: ["CHE", "LIE"], color: "#b71c1c" },
      "Kingdom of Sweden-Norway": { name: "Sweden-Norway", numistaIssuer: "sweden", modernCountries: ["SWE", "NOR"], color: "#0277bd" },
      "Kingdom of Denmark": { name: "Kingdom of Denmark", numistaIssuer: "denmark", modernCountries: ["DNK", "ISL"], color: "#ad1457" },
      "Qing Dynasty": { name: "Qing Dynasty", numistaIssuer: "china-empire", modernCountries: ["CHN", "TWN", "MNG"], color: "#d84315" },
      "British India": { name: "British India", numistaIssuer: "british-india", modernCountries: ["IND", "PAK", "BGD", "MMR", "LKA"], color: "#880e4f" },
      "Qajar Persia": { name: "Qajar Persia", numistaIssuer: "iran", modernCountries: ["IRN", "AFG"], color: "#00695c" },
      "Tokugawa Japan": { name: "Tokugawa Japan", numistaIssuer: "japan", modernCountries: ["JPN"], color: "#bf360c" },
      "United States": { name: "United States", numistaIssuer: "united-states", modernCountries: ["USA"], color: "#1976d2" },
      "Brazil": { name: "Empire of Brazil", numistaIssuer: "brazil", modernCountries: ["BRA"], color: "#388e3c" },
      "Mexico": { name: "Republic of Mexico", numistaIssuer: "mexico", modernCountries: ["MEX"], color: "#6d4c41" },
    },
  },
  {
    startYear: 1867,
    endYear: 1917,
    entities: {
      "Ottoman Empire": { name: "Ottoman Empire", numistaIssuer: "ottoman-empire", modernCountries: ["TUR", "SYR", "IRQ", "SAU", "YEM", "JOR", "LBN", "PSE", "ISR"], color: "#8B0000" },
      "Russian Empire": { name: "Russian Empire", numistaIssuer: "russia-empire", modernCountries: ["RUS", "UKR", "BLR", "LTU", "LVA", "EST", "FIN", "GEO", "ARM", "AZE", "KAZ", "UZB", "TKM", "TJK", "KGZ", "MDA", "POL"], color: "#1a237e" },
      "French Third Republic": { name: "France", numistaIssuer: "france", modernCountries: ["FRA", "DZA", "TUN", "MAR", "MDG", "VNM", "KHM", "LAO"], color: "#1565c0" },
      "Kingdom of Spain": { name: "Kingdom of Spain", numistaIssuer: "spain", modernCountries: ["ESP"], color: "#e65100" },
      "Kingdom of Portugal": { name: "Kingdom of Portugal", numistaIssuer: "portugal", modernCountries: ["PRT", "MOZ", "AGO"], color: "#2e7d32" },
      "Austria-Hungary": { name: "Austria-Hungary", numistaIssuer: "austria", modernCountries: ["AUT", "HUN", "CZE", "SVK", "HRV", "SVN", "BIH", "ROU", "SRB", "MNE", "POL"], color: "#f9a825" },
      "German Empire": { name: "German Empire", numistaIssuer: "germany", modernCountries: ["DEU"], color: "#37474f" },
      "United Kingdom": { name: "United Kingdom", numistaIssuer: "united-kingdom", modernCountries: ["GBR", "IRL", "EGY", "ZAF", "NGA", "GHA", "KEN", "SDN", "AUS", "NZL", "CAN"], color: "#c62828" },
      "Kingdom of Italy": { name: "Kingdom of Italy", numistaIssuer: "italy", modernCountries: ["ITA", "LBY", "ERI", "SOM"], color: "#00838f" },
      "Kingdom of the Netherlands": { name: "Netherlands", numistaIssuer: "netherlands", modernCountries: ["NLD", "IDN"], color: "#ff6f00" },
      "Belgium": { name: "Belgium", numistaIssuer: "belgium", modernCountries: ["BEL", "COD", "RWA", "BDI"], color: "#5d4037" },
      "Switzerland": { name: "Switzerland", numistaIssuer: "switzerland", modernCountries: ["CHE", "LIE"], color: "#b71c1c" },
      "Kingdom of Sweden": { name: "Sweden", numistaIssuer: "sweden", modernCountries: ["SWE"], color: "#0277bd" },
      "Kingdom of Norway": { name: "Norway", numistaIssuer: "norway", modernCountries: ["NOR"], color: "#283593" },
      "Kingdom of Denmark": { name: "Denmark", numistaIssuer: "denmark", modernCountries: ["DNK", "ISL"], color: "#ad1457" },
      "Qing Dynasty": { name: "Qing Dynasty", numistaIssuer: "china-empire", modernCountries: ["CHN", "TWN", "MNG"], color: "#d84315" },
      "British India": { name: "British India", numistaIssuer: "british-india", modernCountries: ["IND", "PAK", "BGD", "MMR", "LKA"], color: "#880e4f" },
      "Qajar Persia": { name: "Qajar Persia", numistaIssuer: "iran", modernCountries: ["IRN"], color: "#00695c" },
      "Empire of Japan": { name: "Empire of Japan", numistaIssuer: "japan", modernCountries: ["JPN", "KOR", "PRK"], color: "#bf360c" },
      "United States": { name: "United States", numistaIssuer: "united-states", modernCountries: ["USA"], color: "#1976d2" },
      "Brazil": { name: "Brazil", numistaIssuer: "brazil", modernCountries: ["BRA"], color: "#388e3c" },
      "Mexico": { name: "Mexico", numistaIssuer: "mexico", modernCountries: ["MEX"], color: "#6d4c41" },
      "Kingdom of Romania": { name: "Romania", numistaIssuer: "romania", modernCountries: ["ROU"], color: "#0d47a1" },
      "Kingdom of Greece": { name: "Greece", numistaIssuer: "greece", modernCountries: ["GRC"], color: "#0097a7" },
      "Kingdom of Bulgaria": { name: "Bulgaria", numistaIssuer: "bulgaria", modernCountries: ["BGR"], color: "#558b2f" },
      "Afghanistan": { name: "Afghanistan", numistaIssuer: "afghanistan", modernCountries: ["AFG"], color: "#4e342e" },
      "Siam": { name: "Kingdom of Siam", numistaIssuer: "thailand", modernCountries: ["THA"], color: "#4527a0" },
      "Ethiopia": { name: "Ethiopian Empire", numistaIssuer: "ethiopia", modernCountries: ["ETH"], color: "#1b5e20" },
      "Argentina": { name: "Argentina", numistaIssuer: "argentina", modernCountries: ["ARG"], color: "#64b5f6" },
      "LUX": { name: "Luxembourg", numistaIssuer: "luxembourg", modernCountries: ["LUX"], color: "#42a5f5" },
    },
  },
  {
    startYear: 1918,
    endYear: 1938,
    entities: {
      "Turkey": { name: "Republic of Turkey", numistaIssuer: "turkey", modernCountries: ["TUR"], color: "#8B0000" },
      "Soviet Union": { name: "Soviet Union (USSR)", numistaIssuer: "ussr", modernCountries: ["RUS", "UKR", "BLR", "LTU", "LVA", "EST", "GEO", "ARM", "AZE", "KAZ", "UZB", "TKM", "TJK", "KGZ", "MDA"], color: "#b71c1c" },
      "France": { name: "France", numistaIssuer: "france", modernCountries: ["FRA", "DZA", "TUN", "MAR", "SYR", "LBN", "MDG", "VNM", "KHM", "LAO"], color: "#1565c0" },
      "Spain": { name: "Spain", numistaIssuer: "spain", modernCountries: ["ESP"], color: "#e65100" },
      "Portugal": { name: "Portugal", numistaIssuer: "portugal", modernCountries: ["PRT", "MOZ", "AGO"], color: "#2e7d32" },
      "Austria": { name: "Republic of Austria", numistaIssuer: "austria", modernCountries: ["AUT"], color: "#f9a825" },
      "Weimar/Nazi Germany": { name: "Germany", numistaIssuer: "germany", modernCountries: ["DEU"], color: "#37474f" },
      "United Kingdom": { name: "United Kingdom", numistaIssuer: "united-kingdom", modernCountries: ["GBR", "EGY", "ZAF", "NGA", "GHA", "KEN", "SDN", "IRQ", "JOR", "PSE", "AUS", "NZL", "CAN"], color: "#c62828" },
      "Kingdom of Italy": { name: "Kingdom of Italy", numistaIssuer: "italy", modernCountries: ["ITA", "LBY", "ERI", "SOM", "ALB", "ETH"], color: "#00838f" },
      "Netherlands": { name: "Netherlands", numistaIssuer: "netherlands", modernCountries: ["NLD", "IDN"], color: "#ff6f00" },
      "Belgium": { name: "Belgium", numistaIssuer: "belgium", modernCountries: ["BEL", "COD", "RWA", "BDI"], color: "#5d4037" },
      "Switzerland": { name: "Switzerland", numistaIssuer: "switzerland", modernCountries: ["CHE", "LIE"], color: "#b71c1c" },
      "Sweden": { name: "Sweden", numistaIssuer: "sweden", modernCountries: ["SWE"], color: "#0277bd" },
      "Norway": { name: "Norway", numistaIssuer: "norway", modernCountries: ["NOR"], color: "#283593" },
      "Denmark": { name: "Denmark", numistaIssuer: "denmark", modernCountries: ["DNK", "ISL"], color: "#ad1457" },
      "Finland": { name: "Finland", numistaIssuer: "finland", modernCountries: ["FIN"], color: "#006064" },
      "Poland": { name: "Poland", numistaIssuer: "poland", modernCountries: ["POL"], color: "#d32f2f" },
      "Czechoslovakia": { name: "Czechoslovakia", numistaIssuer: "czechoslovakia", modernCountries: ["CZE", "SVK"], color: "#303f9f" },
      "Hungary": { name: "Hungary", numistaIssuer: "hungary", modernCountries: ["HUN"], color: "#388e3c" },
      "Yugoslavia": { name: "Yugoslavia", numistaIssuer: "yugoslavia", modernCountries: ["SRB", "HRV", "SVN", "BIH", "MNE", "MKD"], color: "#00695c" },
      "Romania": { name: "Romania", numistaIssuer: "romania", modernCountries: ["ROU"], color: "#0d47a1" },
      "Bulgaria": { name: "Bulgaria", numistaIssuer: "bulgaria", modernCountries: ["BGR"], color: "#558b2f" },
      "Greece": { name: "Greece", numistaIssuer: "greece", modernCountries: ["GRC"], color: "#0097a7" },
      "Republic of China": { name: "Republic of China", numistaIssuer: "china-republic", modernCountries: ["CHN", "TWN", "MNG"], color: "#d84315" },
      "British India": { name: "British India", numistaIssuer: "british-india", modernCountries: ["IND", "PAK", "BGD", "MMR", "LKA"], color: "#880e4f" },
      "Pahlavi Iran": { name: "Iran", numistaIssuer: "iran", modernCountries: ["IRN"], color: "#00695c" },
      "Empire of Japan": { name: "Empire of Japan", numistaIssuer: "japan", modernCountries: ["JPN", "KOR", "PRK"], color: "#bf360c" },
      "United States": { name: "United States", numistaIssuer: "united-states", modernCountries: ["USA"], color: "#1976d2" },
      "Brazil": { name: "Brazil", numistaIssuer: "brazil", modernCountries: ["BRA"], color: "#388e3c" },
      "Mexico": { name: "Mexico", numistaIssuer: "mexico", modernCountries: ["MEX"], color: "#6d4c41" },
      "Ireland": { name: "Irish Free State", numistaIssuer: "ireland", modernCountries: ["IRL"], color: "#2e7d32" },
      "Afghanistan": { name: "Afghanistan", numistaIssuer: "afghanistan", modernCountries: ["AFG"], color: "#4e342e" },
      "Siam": { name: "Kingdom of Siam", numistaIssuer: "thailand", modernCountries: ["THA"], color: "#4527a0" },
      "Saudi Arabia": { name: "Saudi Arabia", numistaIssuer: "saudi-arabia", modernCountries: ["SAU"], color: "#1b5e20" },
      "Argentina": { name: "Argentina", numistaIssuer: "argentina", modernCountries: ["ARG"], color: "#64b5f6" },
    },
  },
  {
    startYear: 1939,
    endYear: 1990,
    entities: {
      "Soviet Union": { name: "Soviet Union (USSR)", numistaIssuer: "ussr", modernCountries: ["RUS", "UKR", "BLR", "LTU", "LVA", "EST", "GEO", "ARM", "AZE", "KAZ", "UZB", "TKM", "TJK", "KGZ", "MDA"], color: "#b71c1c" },
      "United States": { name: "United States", numistaIssuer: "united-states", modernCountries: ["USA"], color: "#1976d2" },
      "United Kingdom": { name: "United Kingdom", numistaIssuer: "united-kingdom", modernCountries: ["GBR"], color: "#c62828" },
      "France": { name: "France", numistaIssuer: "france", modernCountries: ["FRA"], color: "#1565c0" },
      "West Germany": { name: "West Germany", numistaIssuer: "germany", modernCountries: ["DEU"], color: "#37474f" },
      "Italy": { name: "Italy", numistaIssuer: "italy", modernCountries: ["ITA"], color: "#00838f" },
      "Spain": { name: "Spain", numistaIssuer: "spain", modernCountries: ["ESP"], color: "#e65100" },
      "Portugal": { name: "Portugal", numistaIssuer: "portugal", modernCountries: ["PRT"], color: "#2e7d32" },
      "Netherlands": { name: "Netherlands", numistaIssuer: "netherlands", modernCountries: ["NLD"], color: "#ff6f00" },
      "Belgium": { name: "Belgium", numistaIssuer: "belgium", modernCountries: ["BEL"], color: "#5d4037" },
      "Switzerland": { name: "Switzerland", numistaIssuer: "switzerland", modernCountries: ["CHE", "LIE"], color: "#b71c1c" },
      "Austria": { name: "Austria", numistaIssuer: "austria", modernCountries: ["AUT"], color: "#f9a825" },
      "Sweden": { name: "Sweden", numistaIssuer: "sweden", modernCountries: ["SWE"], color: "#0277bd" },
      "Norway": { name: "Norway", numistaIssuer: "norway", modernCountries: ["NOR"], color: "#283593" },
      "Denmark": { name: "Denmark", numistaIssuer: "denmark", modernCountries: ["DNK"], color: "#ad1457" },
      "Finland": { name: "Finland", numistaIssuer: "finland", modernCountries: ["FIN"], color: "#006064" },
      "Iceland": { name: "Iceland", numistaIssuer: "iceland", modernCountries: ["ISL"], color: "#01579b" },
      "Ireland": { name: "Ireland", numistaIssuer: "ireland", modernCountries: ["IRL"], color: "#2e7d32" },
      "Poland": { name: "Poland", numistaIssuer: "poland", modernCountries: ["POL"], color: "#d32f2f" },
      "Czechoslovakia": { name: "Czechoslovakia", numistaIssuer: "czechoslovakia", modernCountries: ["CZE", "SVK"], color: "#303f9f" },
      "Hungary": { name: "Hungary", numistaIssuer: "hungary", modernCountries: ["HUN"], color: "#388e3c" },
      "Yugoslavia": { name: "Yugoslavia", numistaIssuer: "yugoslavia", modernCountries: ["SRB", "HRV", "SVN", "BIH", "MNE", "MKD"], color: "#00695c" },
      "Romania": { name: "Romania", numistaIssuer: "romania", modernCountries: ["ROU"], color: "#0d47a1" },
      "Bulgaria": { name: "Bulgaria", numistaIssuer: "bulgaria", modernCountries: ["BGR"], color: "#558b2f" },
      "Albania": { name: "Albania", numistaIssuer: "albania", modernCountries: ["ALB"], color: "#880e4f" },
      "Greece": { name: "Greece", numistaIssuer: "greece", modernCountries: ["GRC"], color: "#0097a7" },
      "Turkey": { name: "Turkey", numistaIssuer: "turkey", modernCountries: ["TUR"], color: "#8B0000" },
      "China (PRC)": { name: "People's Republic of China", numistaIssuer: "china", modernCountries: ["CHN"], color: "#d84315" },
      "Taiwan (ROC)": { name: "Taiwan", numistaIssuer: "taiwan", modernCountries: ["TWN"], color: "#1a237e" },
      "Japan": { name: "Japan", numistaIssuer: "japan", modernCountries: ["JPN"], color: "#bf360c" },
      "South Korea": { name: "South Korea", numistaIssuer: "south-korea", modernCountries: ["KOR"], color: "#33691e" },
      "North Korea": { name: "North Korea", numistaIssuer: "north-korea", modernCountries: ["PRK"], color: "#4e342e" },
      "India": { name: "India", numistaIssuer: "india", modernCountries: ["IND"], color: "#f57f17" },
      "Pakistan": { name: "Pakistan", numistaIssuer: "pakistan", modernCountries: ["PAK"], color: "#1b5e20" },
      "Iran": { name: "Iran", numistaIssuer: "iran", modernCountries: ["IRN"], color: "#00695c" },
      "Iraq": { name: "Iraq", numistaIssuer: "iraq", modernCountries: ["IRQ"], color: "#795548" },
      "Syria": { name: "Syria", numistaIssuer: "syria", modernCountries: ["SYR"], color: "#455a64" },
      "Egypt": { name: "Egypt", numistaIssuer: "egypt", modernCountries: ["EGY"], color: "#ff8f00" },
      "Israel": { name: "Israel", numistaIssuer: "israel", modernCountries: ["ISR", "PSE"], color: "#1a237e" },
      "Saudi Arabia": { name: "Saudi Arabia", numistaIssuer: "saudi-arabia", modernCountries: ["SAU"], color: "#1b5e20" },
      "Jordan": { name: "Jordan", numistaIssuer: "jordan", modernCountries: ["JOR"], color: "#4e342e" },
      "Lebanon": { name: "Lebanon", numistaIssuer: "lebanon", modernCountries: ["LBN"], color: "#c62828" },
      "Brazil": { name: "Brazil", numistaIssuer: "brazil", modernCountries: ["BRA"], color: "#388e3c" },
      "Mexico": { name: "Mexico", numistaIssuer: "mexico", modernCountries: ["MEX"], color: "#6d4c41" },
      "Argentina": { name: "Argentina", numistaIssuer: "argentina", modernCountries: ["ARG"], color: "#64b5f6" },
      "Canada": { name: "Canada", numistaIssuer: "canada", modernCountries: ["CAN"], color: "#d32f2f" },
      "Australia": { name: "Australia", numistaIssuer: "australia", modernCountries: ["AUS"], color: "#283593" },
      "South Africa": { name: "South Africa", numistaIssuer: "south-africa", modernCountries: ["ZAF"], color: "#4caf50" },
      "Nigeria": { name: "Nigeria", numistaIssuer: "nigeria", modernCountries: ["NGA"], color: "#33691e" },
      "Morocco": { name: "Morocco", numistaIssuer: "morocco", modernCountries: ["MAR"], color: "#e53935" },
      "Algeria": { name: "Algeria", numistaIssuer: "algeria", modernCountries: ["DZA"], color: "#2e7d32" },
      "Tunisia": { name: "Tunisia", numistaIssuer: "tunisia", modernCountries: ["TUN"], color: "#e65100" },
      "Libya": { name: "Libya", numistaIssuer: "libya", modernCountries: ["LBY"], color: "#37474f" },
      "Mongolia": { name: "Mongolia", numistaIssuer: "mongolia", modernCountries: ["MNG"], color: "#0d47a1" },
      "Thailand": { name: "Thailand", numistaIssuer: "thailand", modernCountries: ["THA"], color: "#4527a0" },
      "Indonesia": { name: "Indonesia", numistaIssuer: "indonesia", modernCountries: ["IDN"], color: "#c62828" },
      "Afghanistan": { name: "Afghanistan", numistaIssuer: "afghanistan", modernCountries: ["AFG"], color: "#4e342e" },
      "Ethiopia": { name: "Ethiopia", numistaIssuer: "ethiopia", modernCountries: ["ETH"], color: "#1b5e20" },
      "Luxembourg": { name: "Luxembourg", numistaIssuer: "luxembourg", modernCountries: ["LUX"], color: "#42a5f5" },
      "New Zealand": { name: "New Zealand", numistaIssuer: "new-zealand", modernCountries: ["NZL"], color: "#00695c" },
    },
  },
  {
    startYear: 1991,
    endYear: 2026,
    entities: {
      "Russia": { name: "Russian Federation", numistaIssuer: "russia", modernCountries: ["RUS"], color: "#1a237e" },
      "United States": { name: "United States", numistaIssuer: "united-states", modernCountries: ["USA"], color: "#1976d2" },
      "United Kingdom": { name: "United Kingdom", numistaIssuer: "united-kingdom", modernCountries: ["GBR"], color: "#c62828" },
      "France": { name: "France", numistaIssuer: "france", modernCountries: ["FRA"], color: "#1565c0" },
      "Germany": { name: "Germany", numistaIssuer: "germany", modernCountries: ["DEU"], color: "#37474f" },
      "Italy": { name: "Italy", numistaIssuer: "italy", modernCountries: ["ITA"], color: "#00838f" },
      "Spain": { name: "Spain", numistaIssuer: "spain", modernCountries: ["ESP"], color: "#e65100" },
      "Portugal": { name: "Portugal", numistaIssuer: "portugal", modernCountries: ["PRT"], color: "#2e7d32" },
      "Netherlands": { name: "Netherlands", numistaIssuer: "netherlands", modernCountries: ["NLD"], color: "#ff6f00" },
      "Belgium": { name: "Belgium", numistaIssuer: "belgium", modernCountries: ["BEL"], color: "#5d4037" },
      "Switzerland": { name: "Switzerland", numistaIssuer: "switzerland", modernCountries: ["CHE", "LIE"], color: "#b71c1c" },
      "Austria": { name: "Austria", numistaIssuer: "austria", modernCountries: ["AUT"], color: "#f9a825" },
      "Sweden": { name: "Sweden", numistaIssuer: "sweden", modernCountries: ["SWE"], color: "#0277bd" },
      "Norway": { name: "Norway", numistaIssuer: "norway", modernCountries: ["NOR"], color: "#283593" },
      "Denmark": { name: "Denmark", numistaIssuer: "denmark", modernCountries: ["DNK"], color: "#ad1457" },
      "Finland": { name: "Finland", numistaIssuer: "finland", modernCountries: ["FIN"], color: "#006064" },
      "Iceland": { name: "Iceland", numistaIssuer: "iceland", modernCountries: ["ISL"], color: "#01579b" },
      "Ireland": { name: "Ireland", numistaIssuer: "ireland", modernCountries: ["IRL"], color: "#2e7d32" },
      "Poland": { name: "Poland", numistaIssuer: "poland", modernCountries: ["POL"], color: "#d32f2f" },
      "Czech Republic": { name: "Czech Republic", numistaIssuer: "czech-republic", modernCountries: ["CZE"], color: "#303f9f" },
      "Slovakia": { name: "Slovakia", numistaIssuer: "slovakia", modernCountries: ["SVK"], color: "#1565c0" },
      "Hungary": { name: "Hungary", numistaIssuer: "hungary", modernCountries: ["HUN"], color: "#388e3c" },
      "Romania": { name: "Romania", numistaIssuer: "romania", modernCountries: ["ROU"], color: "#0d47a1" },
      "Bulgaria": { name: "Bulgaria", numistaIssuer: "bulgaria", modernCountries: ["BGR"], color: "#558b2f" },
      "Serbia": { name: "Serbia", numistaIssuer: "serbia", modernCountries: ["SRB"], color: "#c62828" },
      "Croatia": { name: "Croatia", numistaIssuer: "croatia", modernCountries: ["HRV"], color: "#0d47a1" },
      "Slovenia": { name: "Slovenia", numistaIssuer: "slovenia", modernCountries: ["SVN"], color: "#00838f" },
      "Bosnia & Herzegovina": { name: "Bosnia & Herzegovina", numistaIssuer: "bosnia-and-herzegovina", modernCountries: ["BIH"], color: "#1a237e" },
      "Montenegro": { name: "Montenegro", numistaIssuer: "montenegro", modernCountries: ["MNE"], color: "#880e4f" },
      "North Macedonia": { name: "North Macedonia", numistaIssuer: "north-macedonia", modernCountries: ["MKD"], color: "#d84315" },
      "Albania": { name: "Albania", numistaIssuer: "albania", modernCountries: ["ALB"], color: "#880e4f" },
      "Greece": { name: "Greece", numistaIssuer: "greece", modernCountries: ["GRC"], color: "#0097a7" },
      "Turkey": { name: "Turkey", numistaIssuer: "turkey", modernCountries: ["TUR"], color: "#8B0000" },
      "Ukraine": { name: "Ukraine", numistaIssuer: "ukraine", modernCountries: ["UKR"], color: "#fdd835" },
      "Belarus": { name: "Belarus", numistaIssuer: "belarus", modernCountries: ["BLR"], color: "#c62828" },
      "Lithuania": { name: "Lithuania", numistaIssuer: "lithuania", modernCountries: ["LTU"], color: "#f9a825" },
      "Latvia": { name: "Latvia", numistaIssuer: "latvia", modernCountries: ["LVA"], color: "#8e0000" },
      "Estonia": { name: "Estonia", numistaIssuer: "estonia", modernCountries: ["EST"], color: "#1565c0" },
      "Georgia": { name: "Georgia", numistaIssuer: "georgia", modernCountries: ["GEO"], color: "#880e4f" },
      "Armenia": { name: "Armenia", numistaIssuer: "armenia", modernCountries: ["ARM"], color: "#e65100" },
      "Azerbaijan": { name: "Azerbaijan", numistaIssuer: "azerbaijan", modernCountries: ["AZE"], color: "#00838f" },
      "Moldova": { name: "Moldova", numistaIssuer: "moldova", modernCountries: ["MDA"], color: "#fdd835" },
      "China": { name: "People's Republic of China", numistaIssuer: "china", modernCountries: ["CHN"], color: "#d84315" },
      "Taiwan": { name: "Taiwan", numistaIssuer: "taiwan", modernCountries: ["TWN"], color: "#1a237e" },
      "Japan": { name: "Japan", numistaIssuer: "japan", modernCountries: ["JPN"], color: "#bf360c" },
      "South Korea": { name: "South Korea", numistaIssuer: "south-korea", modernCountries: ["KOR"], color: "#33691e" },
      "North Korea": { name: "North Korea", numistaIssuer: "north-korea", modernCountries: ["PRK"], color: "#4e342e" },
      "India": { name: "India", numistaIssuer: "india", modernCountries: ["IND"], color: "#f57f17" },
      "Pakistan": { name: "Pakistan", numistaIssuer: "pakistan", modernCountries: ["PAK"], color: "#1b5e20" },
      "Bangladesh": { name: "Bangladesh", numistaIssuer: "bangladesh", modernCountries: ["BGD"], color: "#2e7d32" },
      "Iran": { name: "Iran", numistaIssuer: "iran", modernCountries: ["IRN"], color: "#00695c" },
      "Iraq": { name: "Iraq", numistaIssuer: "iraq", modernCountries: ["IRQ"], color: "#795548" },
      "Syria": { name: "Syria", numistaIssuer: "syria", modernCountries: ["SYR"], color: "#455a64" },
      "Egypt": { name: "Egypt", numistaIssuer: "egypt", modernCountries: ["EGY"], color: "#ff8f00" },
      "Israel": { name: "Israel", numistaIssuer: "israel", modernCountries: ["ISR", "PSE"], color: "#1a237e" },
      "Saudi Arabia": { name: "Saudi Arabia", numistaIssuer: "saudi-arabia", modernCountries: ["SAU"], color: "#1b5e20" },
      "Jordan": { name: "Jordan", numistaIssuer: "jordan", modernCountries: ["JOR"], color: "#4e342e" },
      "Lebanon": { name: "Lebanon", numistaIssuer: "lebanon", modernCountries: ["LBN"], color: "#c62828" },
      "Brazil": { name: "Brazil", numistaIssuer: "brazil", modernCountries: ["BRA"], color: "#388e3c" },
      "Mexico": { name: "Mexico", numistaIssuer: "mexico", modernCountries: ["MEX"], color: "#6d4c41" },
      "Argentina": { name: "Argentina", numistaIssuer: "argentina", modernCountries: ["ARG"], color: "#64b5f6" },
      "Canada": { name: "Canada", numistaIssuer: "canada", modernCountries: ["CAN"], color: "#d32f2f" },
      "Australia": { name: "Australia", numistaIssuer: "australia", modernCountries: ["AUS"], color: "#283593" },
      "South Africa": { name: "South Africa", numistaIssuer: "south-africa", modernCountries: ["ZAF"], color: "#4caf50" },
      "Nigeria": { name: "Nigeria", numistaIssuer: "nigeria", modernCountries: ["NGA"], color: "#33691e" },
      "Morocco": { name: "Morocco", numistaIssuer: "morocco", modernCountries: ["MAR"], color: "#e53935" },
      "Algeria": { name: "Algeria", numistaIssuer: "algeria", modernCountries: ["DZA"], color: "#2e7d32" },
      "Tunisia": { name: "Tunisia", numistaIssuer: "tunisia", modernCountries: ["TUN"], color: "#e65100" },
      "Libya": { name: "Libya", numistaIssuer: "libya", modernCountries: ["LBY"], color: "#37474f" },
      "Sudan": { name: "Sudan", numistaIssuer: "sudan", modernCountries: ["SDN"], color: "#4e342e" },
      "Kenya": { name: "Kenya", numistaIssuer: "kenya", modernCountries: ["KEN"], color: "#1b5e20" },
      "Ghana": { name: "Ghana", numistaIssuer: "ghana", modernCountries: ["GHA"], color: "#f9a825" },
      "Mongolia": { name: "Mongolia", numistaIssuer: "mongolia", modernCountries: ["MNG"], color: "#0d47a1" },
      "Thailand": { name: "Thailand", numistaIssuer: "thailand", modernCountries: ["THA"], color: "#4527a0" },
      "Indonesia": { name: "Indonesia", numistaIssuer: "indonesia", modernCountries: ["IDN"], color: "#c62828" },
      "Afghanistan": { name: "Afghanistan", numistaIssuer: "afghanistan", modernCountries: ["AFG"], color: "#4e342e" },
      "Ethiopia": { name: "Ethiopia", numistaIssuer: "ethiopia", modernCountries: ["ETH"], color: "#1b5e20" },
      "Kazakhstan": { name: "Kazakhstan", numistaIssuer: "kazakhstan", modernCountries: ["KAZ"], color: "#0097a7" },
      "Uzbekistan": { name: "Uzbekistan", numistaIssuer: "uzbekistan", modernCountries: ["UZB"], color: "#1565c0" },
      "Luxembourg": { name: "Luxembourg", numistaIssuer: "luxembourg", modernCountries: ["LUX"], color: "#42a5f5" },
      "New Zealand": { name: "New Zealand", numistaIssuer: "new-zealand", modernCountries: ["NZL"], color: "#00695c" },
      "Myanmar": { name: "Myanmar", numistaIssuer: "myanmar", modernCountries: ["MMR"], color: "#795548" },
      "Sri Lanka": { name: "Sri Lanka", numistaIssuer: "sri-lanka", modernCountries: ["LKA"], color: "#880e4f" },
      "Cambodia": { name: "Cambodia", numistaIssuer: "cambodia", modernCountries: ["KHM"], color: "#c62828" },
      "Vietnam": { name: "Vietnam", numistaIssuer: "vietnam", modernCountries: ["VNM"], color: "#d32f2f" },
      "Laos": { name: "Laos", numistaIssuer: "laos", modernCountries: ["LAO"], color: "#1a237e" },
      "Madagascar": { name: "Madagascar", numistaIssuer: "madagascar", modernCountries: ["MDG"], color: "#2e7d32" },
      "Yemen": { name: "Yemen", numistaIssuer: "yemen", modernCountries: ["YEM"], color: "#8B0000" },
      "Somalia": { name: "Somalia", numistaIssuer: "somalia", modernCountries: ["SOM"], color: "#0277bd" },
      "Eritrea": { name: "Eritrea", numistaIssuer: "eritrea", modernCountries: ["ERI"], color: "#0097a7" },
    },
  },
];

export function getHistoricalEntitiesForYear(year: number): Record<string, HistoricalEntity> {
  for (const period of HISTORICAL_PERIODS) {
    if (year >= period.startYear && year <= period.endYear) {
      return period.entities;
    }
  }
  return HISTORICAL_PERIODS[HISTORICAL_PERIODS.length - 1].entities;
}

export function getEntityForCountryCode(countryCode: string, year: number): HistoricalEntity | null {
  const entities = getHistoricalEntitiesForYear(year);
  for (const entity of Object.values(entities)) {
    if (entity.modernCountries.includes(countryCode)) {
      return entity;
    }
  }
  return null;
}

export function getCountryColor(countryCode: string, year: number): string | undefined {
  const entity = getEntityForCountryCode(countryCode, year);
  return entity?.color;
}

export const NOTABLE_YEARS = [
  { year: 1700, label: "Age of Empires" },
  { year: 1776, label: "American Independence" },
  { year: 1789, label: "French Revolution" },
  { year: 1815, label: "Congress of Vienna" },
  { year: 1848, label: "Year of Revolutions" },
  { year: 1867, label: "Austro-Hungarian Compromise" },
  { year: 1914, label: "World War I Begins" },
  { year: 1918, label: "End of WWI" },
  { year: 1939, label: "World War II Begins" },
  { year: 1945, label: "End of WWII" },
  { year: 1991, label: "Fall of the USSR" },
  { year: 2002, label: "Euro Currency" },
];
